config/routes.rb
RorBooks::Application.routes.draw do

  root :to => 'google_books#index'
  match 'google_books/grid_data' => 'google_books#grid_data'

end

app/models/book.rb
class Book < ActiveRecord::Base
  require 'googlebooks'
  attr_accessible :title, :authors, :image_link
  
  $BOOK_COUNT    = 40
  $PAGE_COUNT    = 10
  $API_KEY       = 'AIzaSyA1ssxSEUChMJSLjham53CDFThFfnri5Yg'
  $SEARCH_STRING = 'ruby on rails'
  
  def self.reload_books
    books_from_api = []
    (1..$PAGE_COUNT).each do |page_num| 
      books_from_api << GoogleBooks.search( $SEARCH_STRING, {
          :count => $BOOK_COUNT, 
          :page => page_num,
          :api_key => $API_KEY
        }) or raise "Google didn't gave books:("
    end
    unless books_from_api.size.zero?
      transaction do
        self.destroy_all
        books_from_api.each do |books|
          unless books.nil?
            books.each do |book| 
              self.create :title => book.title, :authors => book.authors, :image_link => book.image_link(:zoom => 5)
            end
          end
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/google_books_controller.rb
class GoogleBooksController < ApplicationController
  caches_page :index
  caches_action :grid_data
  
  def index 
  end
  
  def grid_data
    page = (params[:page]).to_i
    rp = (params[:rp]).to_i
    query = params[:query]
    qtype = params[:qtype]
    sortname = params[:sortname]
    sortorder = params[:sortorder]

    if (!sortname)
      sortname = "title"
    end

    if (!sortorder)
      sortorder = "desc"
    end

    if (!page)
      page = 1
    end

    if (!rp)
      rp = 10
    end

    start = ((page-1) * rp).to_i
    query = "%"+query+"%"

    # No search terms provided
    if(query == "%%")
      @books = Book.find(:all,
  	:order => sortname+' '+sortorder,
  	:limit =>rp,
  	:offset =>start
  	)
      count = Book.count(:all)
    end

    # User provided search terms
    if(query != "%%")
        @books = Book.find(:all,
	  :order => sortname+' '+sortorder,
	  :limit =>rp,
  	  :offset =>start,
  	  :conditions=>[qtype +" like ?", query])
	count = Book.count(:all,
	  :conditions=>[qtype +" like ?", query])
    end

    # Construct a hash from the ActiveRecord result
    return_data = Hash.new()
    return_data[:page] = page
    return_data[:total] = count

    return_data[:rows] = @books.collect{|b| {
  			   :cell=>[
             "<img src='#{b.image_link}' />",
             b.title,
             b.authors
           ]
    }}

    # Convert the hash to a json object
    render :text=>return_data.to_json, :layout=>false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/google_books/index.haml
%table{:id => "flex"}

:javascript
  $("#flex").flexigrid
    (
    {
    url: "#{google_books_grid_data_url}",
    dataType: 'json',
    colModel : [
      {display: 'Thumbnail', name : 'image_url', width : 60, sortable : false, align: 'left'},
      {display: 'Title', name : 'title', width : 400, sortable : true, align: 'left'},
      {display: 'Authors', name : 'authors', width : 250, sortable : true, align: 'left'},
    ],
    searchitems : [
      {display: 'Title', name : 'title'},
      {display: 'Authors', name : 'authors'}
    ],
    sortname: "title",
    sortorder: "desc",
    usepager: true,
    title: 'Ruby on Rails books',
    useRp: true,
    rp: 10,
    showTableToggleBtn: true,
    width: 762,
    height: 460
    }
  );

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title= 'RorBooks'
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "flexigrid"
    = javascript_include_tag "application"
    = javascript_include_tag "flexigrid"
    = csrf_meta_tags
  %body
    = yield